# This patch is an example of setting arguments for the cAdvisor container.
# This set of arguments mirrors what the kubelet currently uses for cAdvisor, 
# enables only cpu, memory, diskIO, disk and network metrics, and shows only
# container metrics.
apiVersion: apps/v1 # for Kubernetes versions before 1.9.0 use apps/v1beta2
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: cadvisor
spec:
  template:
    spec:
      containers:
      - name: cadvisor
        args:
          - -storage_driver=statsd
          - -storage_driver_host=otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:8125
